### ISSUE TITLE
New stable release

### ISSUE THREAD

**Issue by Elzor** [Vagabond/gen_smtp#100]
DKIM is not released in 0.9.0. And there is no some other release!
This is normal but unexpected. Please create new release tag.

**Comment by tsloughter** [comment]
i second this. A new release on hex would be great since there hasn't been one since the crypto updates for 18.x were merged.

**Comment by arjan** [comment]
I'll pick this up. I also mailed @Vagabond to give me admin access to the repo to get travis ci working, nothing heard from him so far.
But I'll create the release.

**Comment by arjan** [comment]
Done, https://hex.pm/packages/gen_smtp
