### ISSUE TITLE
Failed compile on OTP 18

### ISSUE THREAD

**Issue by eminarcissus** [Vagabond/gen_smtp#103]
ERROR: Cannot parse OTP Release version string: 18
ERROR: compile failed while processing /Users/home/developing/test/deps/gen_smtp: rebar_abort

I think I did have it compiled couple days ago, don't know what's happening here.

**Comment by arjan** [comment]
That is strange, it works for me.
Can you check which rebar version it uses? Maybe it uses the rebar from your parent project, which is too old? (older versions indeed croaked when the OTP version string did not start with "R")

**Comment by eminarcissus** [comment]
Indeed I reference it from a elixir lib. so don't know rebar version it does use, in my system path the rebar version is rebar 2.1.0-pre R16B 20130708_152514 git 2.1.0-pre-140-g620c4b0, which is installed from homebrew I believe.
I changed back to use 0.9.0 now and it compiles without any problem though

**Comment by arjan** [comment]
If @Vagabond grants me admin permissions of this repo, I'll hook it up to Travis CI.
We should switch to rebar3 anyway..

**Comment by arjan** [comment]
Try using the 0.10.0 version from hex.pm, it should work.
