### ISSUE TITLE
smtp_util:generate_message_id() depends on node's lifetime on Erlang >= 18

### ISSUE THREAD

**Issue by ElectronicRU** [Vagabond/gen_smtp#113]
The function uses unique_integer() which is only guaranteed to be unique within one instance of Erlang runtime, but should a restart occur, it would regenerate much the same ID's with extremely high probability. This leads to Message-IDs collision.

**Comment by Vagabond** [comment]
Yeah, looks like someone goofed when trying to avoid using deprecated erlang:now(), ugh.

**Comment by ElectronicRU** [comment]
Should be fine if we go erlang:monotonic_time() + erlang:unique_integer() or somesuch, but why not just use strong_rand_bytes.
