### ISSUE TITLE
allow_bare_newlines

### ISSUE THREAD

**Issue by sledwich** [Vagabond/gen_smtp#121]
Having a problem with incoming email which is throwing error 

451 Bare newline detected (in reply to end of DATA command))

We can see there appears to be an option called allow_bare_newlines but we cant seem to find how to properly set this?

Would you mind giving me a pointer to help get this resolved. 

Thank you

**Comment by seriyps** [comment]
https://github.com/Vagabond/gen_smtp#server-example

> You can configure the server in general, each SMTP session, and the callback module, for example:
>
> `gen_smtp_server:start(smtp_server_example, [[{sessionoptions, [{allow_bare_newlines, fix}, {callbackoptions, [{parse, true}]}]}]]).`
> This configures the session to fix bare newlines (other options are 'strip', 'true' and 'false', false rejects emails with bare newlines, true passes them through unmodified and strip removes them) and tells the callback module to run the MIME decoder on the email once its been received.

**Comment by sledwich** [comment]
Thank you very much! will give this a try.

**Comment by seriyps** [comment]
Looks like this can be closed
