### ISSUE TITLE
Iconv dependency.

### ISSUE THREAD

**Issue by benwilson512** [Vagabond/gen_smtp#123]
https://github.com/Vagabond/gen_smtp/blob/master/src/mimemail.erl makes significant use of an `:iconv` module, but no such dependency is listed on either hex or in the readme.

`zotonic/eiconv` is listed in the rebar config, but it's incompatible with the `iconv` that is actually on hex. I'm having issues with it specifically building its nif properly on ubuntu and was hoping that the `iconv` dep on hex would work instead, but it does not.

**Comment by mworrell** [comment]
The `iconv` module is optional. At zotonic we are indeed using `eiconv`, which worked (or works) better with large data blobs.

It is unclear to me why you can't use the rebar-referenced `eiconv` module?

**Comment by benwilson512** [comment]
Attempting run a release built on ubuntu with OTP 19.2 and the `eiconv` project is resulting in
```
	{{badmatch,{error,{load_failed,"Failed to load NIF library: '/u/releases/sensetra/lib/eiconv-1.1/priv/eiconv_nif.so: cannot open shared object file: No such file or directory'"}}},[{eiconv,init,0,[{file,"/u/apps/sensetra/deps/eiconv/src/eiconv.erl"},{line,18}]},{init,'-run_on_load_handlers/2-fun-0-',1,[]}]}
```

When I look on the build server there is no `priv` amongst the build artifacts for that library. I was hoping a more up to date version would build correctly.

**Comment by mworrell** [comment]
We don't seem to have problems building it with rebar3 (and rebar2) in our projects, how are you building your project?  Maybe you can file an issue with more detailed info at https://github.com/zotonic/eiconv

**Comment by mworrell** [comment]
Having said that I see that zotonic/eiconv is quite behind mmzeeman/eiconv.  I asked @mmzeeman if it is safe to update.

**Comment by benwilson512** [comment]
I appreciate your patience. The project you're linking to has disabled its issues page, and has had no commits for 3 years, it seems unlikely I'm going to get much help there.

Working on a reproducible example.

**Comment by mworrell** [comment]
The issues should be accessible now.

**Comment by benwilson512** [comment]
After further investigation it seems to be an issue with rebar. Thanks!
