### ISSUE TITLE
{missing_requirement,"smtp.gmail.com",tls}

### ISSUE THREAD

**Issue by dcy** [Vagabond/gen_smtp#124]
Hi!
When i don't use tls:
```
{permanent_failure,"smtp.gmail.com",
                          <<"530-5.5.1 Authentication Required. Learn more at\r\n530 5.5.1  https://support.google.com/mail"...>>}}
```
When i use tls:
```
{error,retries_exceeded,                                                                             
       {missing_requirement,"smtp.gmail.com",tls}}
```

**Comment by Vagabond** [comment]
can you please show how you're connecting (usernames and passwords redacted). Also, using rp() to print that return value in full so we can see the URL the SMTP server is returning would be good.

**Comment by dcy** [comment]
```
    Receivers = ["766320183@qq.com"],
    Opts = [{relay, "smtp.gmail.com"}, {username, "guangzhouligo@gmail.com"}, {password, "passwd"}],
    Body = <<"Hello, Nice to meet you">>,
    Result = gen_smtp_client:send_blocking({"guangzhouligo@gmail.com", Receivers, Body}, Opts),
    ?TRACE_VAR(Result),
```
The same code works in my desktop computer, But it does not work in the server
```
My print's "Result" is {error,no_more_hosts,
                           {permanent_failure,"smtp.gmail.com",
                               <<"530 5.7.0 Must issue a STARTTLS command first. v128sm15637217pgb.20 - gsmtp\r\n">>}}
******
```
So i change ```Opts``` to ```[{relay, "smtp.gmail.com"}, {username, "guangzhouligo@gmail.com"}, {password, "passwd"}, {tls, always}]```, It will be:
```
My print's "Result" is {error,retries_exceeded,
                              {missing_requirement,"smtp.gmail.com",tls}}

```

**Comment by Vagabond** [comment]
You likely need to configure a different port, like 587:

https://support.google.com/a/answer/176600?hl=en

**Comment by dcy** [comment]
Thanks! ```{port, 587}``` works

**Comment by dcy** [comment]
@Vagabond  By the way, Does gen_smtp support ```proxy``` like [hackney proxy](https://github.com/benoitc/hackney#proxy-a-connection) ?
