### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by duics** [Vagabond/gen_smtp#125]
Changes introduced in #115 made it possible to authenticate against smtp.outlook365.com, which was a very useful improvement, and I thank you for that.

Would it be possible to make a new release of gen_smtp so that it's not neccessary to depend on the master branch?

**Comment by mworrell** [comment]
Tagged 3e1e7e4  with 0.12.0

**Comment by arjan** [comment]
I re-pushed the tag because the `.app.src` file still said `0.11.0`. Also published on hex.pm
