### ISSUE TITLE
Help for use trace function in gen_smpt_client.erl

### ISSUE THREAD

**Issue by ethrbh** [Vagabond/gen_smtp#133]
hello,

I just started to use this project, and of course, the first attempt when I tried send email was not success. No error was appeared in the Erlang shell, just got ok

	(igs@ethrbh-VirtualBox)22> gen_smtp_client:send({"ToEmail", "FromEmail", "Subject: testing\r\nFrom: FromMe \r\nTo: Some Dude \r\n\r\nThis is the email body"}, [{relay, "smtp.gmail.com"}, {username, "MyGmailAccount"}, {password, "MyGmailPwd"}, {auth, always}, {port, 587}]).
	{ok,<0.1037.0>}
	(igs@ethrbh-VirtualBox)23> 

Because no email was received, I started to look at the source file of this application, and I saw there is a trace function what probably I can start use for debugging. Looking the trace function, it gets the trace_fun from the Options proplist. In the Erlang shell, I tried create Fun and passing this through, but got always "badarity"

	(igs@ethrbh-VirtualBox)17> TraceFun=fun()->"io:format" end.
	#Fun<erl_eval.20.99386804>
	
	(igs@ethrbh-VirtualBox)22> gen_smtp_client:send({"ToEmail", "FromEmail", "Subject: testing\r\nFrom: FromMe \r\nTo: Some Dude \r\n\r\nThis is the email body"}, [{relay, "smtp.gmail.com"}, {username, "MyGmailAccount"}, {password, "MyGmailPwd"}, {auth, always}, {port, 587}, {trace_fun, TraceFun}]).
	{ok,<0.1027.0>}
	** exception error: interpreted function with arity 0 called with two arguments
		 in function  gen_smtp_client:trace/3 (src/gen_smtp_client.erl, line 695)
		 in call from gen_smtp_client:send_it/2 (src/gen_smtp_client.erl, line 182)
		 in call from gen_smtp_client:send_it_nonblock/3 (src/gen_smtp_client.erl, line 114)
	(igs@ethrbh-VirtualBox)19> 14:17:50.075 [error] Error in process <0.1027.0> on node 'igs@ethrbh-VirtualBox' with exit value:
	{{badarity,{#Fun<erl_eval.20.99386804>,["MX records for ~s are ~p~n",["smtp.gmail.com",[{10,"66.102.1.109"},{10,"66.102.1.108"}]]]}},[{gen_smtp_client,trace,3,[{file,"src/gen_smtp_client.erl"},{line,695}]},{gen_smtp_client,send_it,2,[{file,"src/gen_smtp_client.erl"},{line,182}]},{gen_smtp_client,send_it_nonblock,3,[{file,"src/gen_smtp_client.erl"},{line,114}]}]}

Maybe I just don't see what I did wrong, thus I would like turn to you for getting some lights.

thanks for your help,
/Robi

**Comment by ethrbh** [comment]
hello,

And here is the answer from me, to me :-)

The Fun should be like this:
    TraceFun=fun io:format/2.

Now I can see the trace messages.

thanks,
/Robi

**Comment by seriyps** [comment]
I would suggest you to try `gen_smtp_client:send_blocking/2`, because `gen_smtp_client:send/2` is asynchronous.

Also, the way you provide trace function is incorrect. Try `TraceFun = fun io:format/2.` or `TraceFun = fun(Format, Args) -> io:format(Format, Args) end.`

**Comment by ethrbh** [comment]
hello Sergey,

Thanks for your answer. I will do that.

thanks,
/Robi
