### ISSUE TITLE
Inline images: Content-ID and inline disposition

### ISSUE THREAD

**Issue by skosch** [Vagabond/gen_smtp#135]
I would like to send an email with an inlined logo. Here is what I am currently able to get

```
--_=2s3h5a385h585m640z706k5y5y5q1h1r=_
Content-Type: image/png
Content-Disposition: attachment; filename=logo.png
Content-Transfer-Encoding: base64

iVBORw0KGgoAAA ...
```
... and here is what I would like instead:
```
--_=2s3h5a385h585m640z706k5y5y5q1h1r=_
Content-Type: image/png
Content-Disposition: inline; filename=logo.png
Content-Transfer-Encoding: base64
Content-ID: <logo.png@01D32254.46E0EF20>

iVBORw0KGgoAAA ...
```
What exactly do my `Parts` and their parameters need to look like when I call `encode({Type, Subtype, Headers, ContentTypeParams, Parts}, Options)` to achieve the above? Is this possible at all?

**Comment by mworrell** [comment]
It is a bit convoluted, but I think you will be able to find your answer here in this code https://github.com/zotonic/zotonic/blob/master/apps/zotonic_core/src/smtp/z_email_embed.erl

**Comment by seriyps** [comment]
Yeah, particularly on those lines I guess https://github.com/zotonic/zotonic/blob/master/apps/zotonic_core/src/smtp/z_email_embed.erl#L107-L125

**Comment by mworrell** [comment]
We use this code to inline all images in email sent by Zotonic. In this way the recipient doesn't see half emails, or that "load external data" (or similar) button.

**Comment by skosch** [comment]
Oh, so it goes into headers, not parameters. :thinking: That's very helpful @mworrell, I think that should solve my problem. Now onto dealing with nested multipart types ...

**Comment by Vagabond** [comment]
It might be nice to have some functions for constructing large multipart hierarchies as part of the library, if anyone feels ambitious.

**Comment by seriyps** [comment]
@Vagabond yeah, that sounds like a good idea. Maybe even hide whole mimemail structure under a set of getter/setter/constructor functions...
