### ISSUE TITLE
gen_smtp_client:send_blocking() unable to send email 

### ISSUE THREAD

**Issue by dileepravindran** [Vagabond/gen_smtp#137]
Hi , i'm trying to send email using gen_smtp_client:send_blocking()  or gen_smtp_client:send() function .

issue https://github.com/Vagabond/gen_smtp/issues/40 has an example mentioned . trying out with my email id's 

Email = {
    "sender@gmail.com",
    ["receiver@gmail.com"],
    <<"From: MW <sender@gmail.com>\r\nTo: MW <receiver@gmail.com>\r\nSubject: Test\r\n\r\nDit is een test.">>
},
Options = [
    {ssl,true},
    {no_mx_lookups,true},
    {relay,"smtp.gmail.com"},
    {username,"sender@gmail.com"},
    {password,"xxxx"},
    {auth,always}
],
gen_smtp_client:send_blocking(Email, Options). 

i'm getting the following error. 
inet_gethost[3201]: WARNING:Timeout waiting for child process to die, ignoring child (pid = 3205).
{error,retries_exceeded,
       {network_failure,"smtp.gmail.com",{error,nxdomain}}}

Could some help me out with a proper example  for sending email with or without ssl enabled.

**Comment by seriyps** [comment]
Why do you have `no_mx_lookups` option on?

**Comment by dileepravindran** [comment]
i'm just using the example by only changing the mail ID's. i tried with out {no_mx_lookups,true}, 

now i get this error
** exception error: {error,retries_exceeded,
                           {network_failure,"40.100.136.146",{error,timeout}}}

i tried telnet'ing smtp.gmail.com 25 . seem to be fine

Trying 74.125.200.109...
Connected to gmail-smtp-msa.l.google.com.
Escape character is '^]'.
220 smtp.gmail.com ESMTP a17sm15873549pfk.173 - gsmtp

**Comment by seriyps** [comment]
You may try to add `{trace_fun, fun io:format/2}` to get some debug output. But this looks strange anyway

**Comment by dileepravindran** [comment]
okay. added the option {trace_fun, fun io:format/2} .

this is what the trace looks like:

MX records for smtp.live.com are []
scheduling smtp.live.com for retry (1 of 1)
inet_gethost[5052]: WARNING:Timeout waiting for child process to die, ignoring child (pid = 5053).
retries for smtp.live.com exceeded (1 of 1)
{error,retries_exceeded,
       {network_failure,"smtp.live.com",{error,nxdomain}}}

**Comment by seriyps** [comment]
In your 1st example you use gmail and here it's live.com. May you, please, show what code do you run plus the output?

**Comment by dileepravindran** [comment]
sorry abt that i was trying with smtp.live.com. i changed it smtp.gmail.com. the out put seem to be similar 

MX records for smtp.gmail.com are []
scheduling smtp.gmail.com for retry (1 of 1)
inet_gethost[5145]: WARNING:Timeout waiting for child process to die, ignoring child (pid = 5146).
retries for smtp.gmail.com exceeded (1 of 1)
{error,retries_exceeded,
       {network_failure,"smtp.gmail.com",{error,nxdomain}}}

**Comment by dileepravindran** [comment]
this is the exact i'm using for the above output 
Email = {
    "sender@gmail.com",
    ["receiver@gmail.com"],
    <<"From: MW <sender@gmail.com>\r\nTo: MW <receiver@gmail.com>\r\nSubject: Test\r\n\r\nDit is een test.">>
},
Options = [
    {ssl,true},
    {trace_fun, fun io:format/2},
    {relay,"smtp.gmail.com"},
    {username,"sender@gmail.com"},
    {password,"xxxxx"},
    {auth,always}
],
gen_smtp_client:send_blocking(Email, Options).

**Comment by seriyps** [comment]
empty list of MX records and this `inet_gethost[5145]: WARNING` suggests me that you have some troubles with DNS resolver in your installation.

May you describe your environment in more details?

- Which OS do you use?
- Which version of erlang?
- How did you install erlang?
- Do you use erlang shell or run this code from erlang module?
- Do you use rebar/rebar3?
- What is the output of `nslookup -type=mx smtp.gmail.com`?

**Comment by dileepravindran** [comment]
1)Which OS do you use?
        Linux ubuntu 4.8.0-22-generic #24-Ubuntu SMP Sat Oct 8 09:15:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

2)Which version of erlang?
         version 19

3)How did you install erlang?
          installed using source code 

4)Do you use erlang shell or run this code from erlang module?
         ran it through erlang module 

5)Do you use rebar/rebar3?
          uses rebar3

6)What is the output of nslookup -type=mx smtp.gmail.com?
        ;; connection timed out; no servers could be reached

**Comment by seriyps** [comment]
Ok, p.p. 6 looks suspicious. Maybe you have some problems with DNS server... Erlang uses system's DNS settings by default. You may read through http://erlang.org/doc/apps/erts/inet_cfg.html, but I don't know how to help you more.

**Comment by dileepravindran** [comment]
thanks for the quick reply . let me check on the DNS part. will get back if i find something

**Comment by dileepravindran** [comment]
looks like DNS issue. was able to resolve it. now  nslookup -type=mx smtp.gmail.com give me proper output :Server:		103.8.44.5
Address:	103.8.44.5#53

Non-authoritative answer:
smtp.gmail.com	canonical name = gmail-smtp-msa.l.google.com.

Authoritative answers can be found from:
l.google.com
	origin = ns3.google.com
	mail addr = dns-admin.google.com
	serial = 173638353
	refresh = 900
	retry = 900
	expire = 1800
	minimum = 60


i was able to send out email . 
thanks!

**Comment by seriyps** [comment]
:+1: Please, close the ticket if the problem was solved
