### ISSUE TITLE
Daily user sending quota exceeded 

### ISSUE THREAD

**Issue by dileepravindran** [Vagabond/gen_smtp#140]
while trying to send email - i'm getting this message after sending several emails

{{nocatch,{permanent_failure,<<"550 5.4.5 Daily user sending quota exceeded. o65sm25351206pga.71 - gsmtp\r\n">>}}

is there any daily limit to send emails for the   domain smtp.gmail.com ?

**Comment by seriyps** [comment]
It's not a gen_smtp limitation. This message is what google server returns if you send too many mails through it: https://productforums.google.com/forum/#!topic/gmail/qJH8FXzxyA4
