### ISSUE TITLE
where "mx203.inbound-mx.net" domain come from?

### ISSUE THREAD

**Issue by PearceDuan** [Vagabond/gen_smtp#142]
```
gen_smtp_client:send_blocking({<<"noreply@dasudian.com">>, [<<"dx@dasudian.com">>], <<"Subject: EmailTest\r\nFrom: test@dasudian.com\r\nTo: dx@dasudian.com\r\nContent-Type: text/html;\r\n\tcharset=us-ascii\r\nMIME-Version: 1.0\r\nDate: Fri, 12 Jan 2018 15:14:56 +0800\r\nMessage-ID: <9ce21850fc0d4ee5d2981354f776190a@dx>\r\n\r\n<p>Hello 33333!!!</p>">>}, [{relay, <<"smtp.mxhichina.com.com">>},{username, <<"test@dasudian.com">>},{password, <<"yourpassword">>}, {port, 25}]).
```
when I call `gen_smtp_client:send_blocking/2`, pass all parameters correct but `relay` wrong(with extra `.com`).
Normally, it will return {error,timeout} when `socket:connect(tcp, "smtp.mxhichina.com.com", 25, [binary,{packet,line},{keepalive,true},{active,false}], 5000)` was called,  
But now, it return {ok, Pid}.   
Through debug info, I found it will try to connect a domain like `mx203.inbound-mx.net` when `scoket:connect/5` was called.  
I don't know where `mx203.inbound-mx.net` come from ?  
Thanks!

**Comment by mworrell** [comment]
That comes from the MX record:

```
$ dig mx smtp.mxhichina.com.com

; <<>> DiG 9.9.5-3ubuntu0.15-Ubuntu <<>> mx smtp.mxhichina.com.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4561
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;smtp.mxhichina.com.com.		IN	MX

;; ANSWER SECTION:
smtp.mxhichina.com.com.	60	IN	MX	10 mx203.inbound-mx.net.
smtp.mxhichina.com.com.	60	IN	MX	10 mx203.inbound-mx.org.
```

**Comment by nimrod-cohen** [comment]
I have the same problem, not sure why every call to non existent domain returns these two MX records

**Comment by seriyps** [comment]
Probably because it is an existing domain? It might not have A record but still have MX record in DNS? @nimrod-cohen do you have a problem with `smtp.mxhichina.com.com` or some other domain?

**Comment by nimrod-cohen** [comment]
@seriyps 
It doesn't matter which domain I'm asking about, i can do: basdjafiefghi.slfhdkhf.com it will still reply the same answer. The domain definitely doesn't exist, it seems like its some sort of default response on CentOS, because my dev machine (mac) doesn't return anything on a non-existent domain.

**Comment by seriyps** [comment]
@nimrod-cohen that's interesting. I doubt it's specific for gen_smtp. Probably some provider's DNS settings.

What would `resolvectl` and `dig MX basdjafiefghi.slfhdkhf.com` commands say?

**Comment by nimrod-cohen** [comment]
@seriyps, indeed interesting:
 resolvectl is not available on centos
 dig is properly returning empty.
`host -t MX ax3ulfkjdaaagmaiaaala.com` returns this:
ax3ulfkjdaaagmaiaaala.com.com mail is handled by 10 mx203.inbound-mx.net.
ax3ulfkjdaaagmaiaaala.com.com mail is handled by 10 mx203.inbound-mx.org.

so this is definitely coming form the OS and not from PHP.
