### ISSUE TITLE
Gmail example still correct?

### ISSUE THREAD

**Issue by ebengt** [Vagabond/gen_smtp#151]
Greetings,

Should the Gmail example in README be updated?

I am testing the Gmail example. I think this should work:
send( SSL ) ->
        On = (SSL =:= ssl),
        gen_smtp_client:send_blocking(email(), [{relay, "smtp.gmail.com"}, username(), password(), {ssl, On}]).

I get:
1> mylib:send(ssl).
{error,no_more_hosts,
       {permanent_failure,"smtp.gmail.com",
                          <<"530-5.5.1 Authentication Required. Learn more at\r\n530 5.5.1  https://support.google.com/mail"...>>}}
2> mylib:send(nossl).
{error,no_more_hosts,
       {permanent_failure,"smtp.gmail.com",
                          <<"530-5.5.1 Authentication Required. Learn more at\r\n530 5.5.1  https://support.google.com/mail"...>>}}

If I change the account settings to allow less secure apps both SSL true and false work:
<<"2.0.0 OK 1530972198 q70-v6sm18381771wmd.45 - gsmtp\r\n">>

So, perhaps README should be updated with the information that the setting should be less secure apps?
Or am I doing it wrong?

**Comment by Vagabond** [comment]
It likely has changed. Do you know what they want us to do to be 'more secure'? The gmail docs aren't very clear:

https://support.google.com/accounts/answer/6010255?hl=en

It looks like they want you to send an Oauth2 token as a credential to be "more secure".

**Comment by Vagabond** [comment]
So, gen_smtp *does* have XOAUTH2 support, but I've never used it.

https://developers.google.com/gmail/imap/xoauth2-protocol

If you get something working, let me know and we can update the README.

**Comment by ebengt** [comment]
Greetings,

Thank you very much for taking the time and investigating my problem. I read the links you suggested and decided that ‘allow less secure' was exactly what I wanted. The lessening of security comes from giving my password to the application, but in this case that is exactly what I want to do. It is my application, and i trust it.

I made a slight modification to the gen_smtp README, explaining the new Gmail how and why. But when I tried my code it no longer worked. I have changed the account back to ‘allow less secure’ but still get auth failures. If it was not for all the successful test emails I still have from yesterday, I would think it impossible.

I will look into OAUTH, but first I want what I had yesterday back.


bengt

**Comment by ebengt** [comment]
Greetings,

No news about OAUTH2, but I did get the example in README working. I had to set Gmail to ‘allow less secure’. That did not work right away, which explains why I thought there was something else going on.

If you add ‘allow less secure’ to README everything will be fine.

I will put OAUTH2 on my pile of things to do when work permits.

Best Wishes,
bengt

**Comment by benbro** [comment]
[Instructions](https://github.com/Vagabond/gen_smtp/pull/76) for OAUTH2 with Gmail.

**Comment by ebengt** [comment]
Sorry for the delay, but I am moving house and the new flat does not yet have internet (nor kitchen).
I promise to make a PR, but right now is a bit inconvenient.


Best Wishes,
bengt

**Comment by mworrell** [comment]
Closing for now.
