### ISSUE TITLE
'TLS client: In state hello received SERVER ALERT: Fatal - Handshake Failure'

### ISSUE THREAD

**Issue by caogenwang** [Vagabond/gen_smtp#164]
I have no idea about this error when I use gen_smtp to send a mail.

```
09:54:32.853 [info] ['TLS', 32, 'client', 58, 32, 73, 110, 32, 115, 116, 97, 116, 101, 32, 'hello', 32,'received SERVER ALERT: Fatal - Handshake Failure', 10]
```

**Comment by mworrell** [comment]
Could you post a more complete error log?

In general this could be one of many things, but on top of my list are:

 * interrupted traffic (packet loss or anything else)
 * incompatible TLS / SSL versions (try the newest Erlang release you can use)
 * or might even be connecting with TLS to a non TLS server

**Comment by caogenwang** [comment]
Thanks for your attention.There's no more error log.I am  not familiar with TLS/SSL.I just wanted to make a test.Now I give up TSL/SSL protocol and send a e-mail successfully.Thanks again.

**Comment by mworrell** [comment]
Closing for now.
