### ISSUE TITLE
Conflict with Erlang/OTP-22 socket module

### ISSUE THREAD

**Issue by dmorneau** [Vagabond/gen_smtp#168]
Erlang/OTP-22 is introducing a new module called "socket", documented here (as of 22-rc2): 

http://erlang.org/documentation/doc-11.0-rc2/erts-10.4/doc/html/socket.html

This module conflicts with the module called "socket" in gen_smtp, preventing us from using the library when running on 22-rc2 (undefined function error for socket:connect/5). Would it be possible to rename the module to something like "gen_smtp_socket" perhaps?

**Comment by Vagabond** [comment]
Yeah. I don't know when I'll get around to it though, so if you wanted to make a PR that'd make it go faster.

**Comment by mworrell** [comment]
I will have a go at it.

**Comment by mworrell** [comment]
Added a merge request in #169

**Comment by dmorneau** [comment]
Fantastic, thank you!

**Comment by mworrell** [comment]
@dmorneau Thanks for reporting the issue!

**Comment by dmorneau** [comment]
Hello! @vagabond would it be possible to push a release to hex now that OTP-22 is out?

**Comment by ckruse** [comment]
Releasing a new version because of this would be pretty nice, yes.

**Comment by mworrell** [comment]
If @Vagabond doesn't have time, then @arjan can you have a look at making a new release and pushing it to Hex?

**Comment by arjan** [comment]
on it!

**Comment by arjan** [comment]
Done
