### ISSUE TITLE
oauth support

### ISSUE THREAD

**Issue by benbro** [Vagabond/gen_smtp#70]
Is there a chance for oauth support when connecting to SMTP servers?
https://developers.google.com/gmail/oauth_overview
https://developers.google.com/gmail/xoauth2_protocol
2-legged auth
https://developers.google.com/gmail/oauth_protocol

Erlang oauth 2.0 client
https://github.com/kivra/oauth2_client

I currently need to save the email password in plain text in the Erlang code.
It can be much more secure if I'll be able to use an oauth token.

Thanks

**Comment by hachreak** [comment]
:+1: 
I encountered that problem with Gmail.. T_T
I resolved the option to permit the login from "less secure" application.
