### ISSUE TITLE
How to include a text version of the message ?

### ISSUE THREAD

**Issue by TheSquad** [Vagabond/gen_smtp#82]
Hello,
I'm using a tool to get the email score to avoid landing in SPAM...
I'm almost perfect with gen_smtp.
However SpamAssassin requires a text version of the email :
`Message only has text/html MIME parts. 
You should also include a text version of your message (text/plain)`
How can I do that with gen_smtp ? I haven't found anything in the examples or test to perform this.

Thanks for your help.

**Comment by seriyps** [comment]
https://tools.ietf.org/html/rfc2046#section-5.1.4
```erlang
{<<"multipart">>,<<"alternative">>,
 [{<<"From">>, From},
  {<<"To">>, To},
  {<<"Subject">>, Subject}],
 [],
 [{<<"text">>, <<"plain">>,
   [{<<"Content-Type">>, <<"text/plain;charset=utf-8">>},
    {<<"Content-Disposition">>, <<"inline">>}],
   [],
   PlainBody},
  {<<"text">>, <<"html">>,
   [{<<"Content-Type">>, <<"text/html;charset=utf-8">>},
    {<<"Content-Disposition">>, <<"inline">>}],
   [],
   HtmlBody}]}
```

**Comment by TheSquad** [comment]
Thanks !!
