### ISSUE TITLE
Simple email send is not working : (

### ISSUE THREAD

**Issue by AntonVelmozhniy** [Vagabond/gen_smtp#86]
Hi!

My actions:

Email = {
    "my@gmail.com",
    ["my@gmail.com"],
    <<"From: MW <my@gmail.com>\r\nTo: MW <my@gmail.com>\r\nSubject: Test\r\n\r\nDit is een test.">>
    },
    Options = [
        {ssl,true},
        {no_mx_lookups,true},
        {relay,"smtp.gmail.com"},
        {username,"my@gmail.com"},
        {password,"my_pass"},
        {auth,always},
        {port,25}
    ],
    gen_smtp_client:send(Email, Options).

And got this: {error,retries_exceeded, {network_failure,"smtp.gmail.com",{error,timeout}}}

What am I doing wrong?

**Comment by seriyps** [comment]
```
$ telnet smtp.gmail.com 25
Trying 64.233.163.109...
Trying 64.233.163.108...
Trying 2a00:1450:4010:c06::6c...
telnet: Unable to connect to remote host: Network is unreachable
```
SMTP + TLS ports for smtp.gmail.com are 465 or 587
https://support.google.com/a/answer/176600

**Comment by mworrell** [comment]
Looks like you can not connect to `smtp.gmail.com` or that they are overloaded.

Retry on a later moment or check in *telnet* if you can connect to `smtp.gmail.com`

Ahh.... @seriyps is faster than me :+1:

**Comment by mworrell** [comment]
Closing issue.

**Comment by AntonVelmozhniy** [comment]
Ok, i did not pass port value, not sure if I do it right anyway. And i get this: exception error: {error,retries_exceeded,
                        {network_failure,"smtp.gmail.com",
                            {error,ssl_not_started}}}

**Comment by AntonVelmozhniy** [comment]
Is it right, should it work?
It does not for me.
Email = {
"my@gmail.com",
["my@gmail.com"],
<<"From: MW my@gmail.com\r\nTo: MW my@gmail.com\r\nSubject: Test\r\n\r\nDit is een test.">>
},
Options = [
{ssl,true},
{no_mx_lookups,true},
{relay,"smtp.gmail.com"},
{username,"my@gmail.com"},
{password,"my_pass"},
{auth,always},
{port,465 }
],
gen_smtp_client:send(Email, Options).

**Comment by mworrell** [comment]
Try to do this:

```Erlang
			application:start(crypto),
			application:start(public_key),
			application:start(ssl),
```
 And see if you get any errors. Note that on some Linux versions *erlang-ssl* is a separate install.
