### ISSUE TITLE
Deprecated time:now()

### ISSUE THREAD

**Issue by technion** [Vagabond/gen_smtp#91]
Hi,

On R18, I'm getting this error in several parts of code:

src/smtp_util.erl:113: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information

I've created a fix in this branch:
https://github.com/technion/gen_smtp/tree/timeupdate

The fix doesn't just blindly change to the new timestamp, it includes a wrapper to ensure support for existing versions. Given the intent of erlang:now() in the code has been to produce unique integers, it targets that rather than just identifying the time.

I needed however to place this in a new file in order to silence compiler warnings.

Regardless, the reason I haven't made a PR is because attempting to run tests just gives me several crashes - although they fail on my system regardless of this commit. Example:

```
in call from gen_smtp_client:'-session_start_test_/0-fun-77-'/1 (src/gen_smtp_client.erl, line 842)
**exit:{{badkey,[{crypto,sign,[sha512,
...
```

Any feedback appreciated. If you have no issue with tests I'm happy to turn it into a PR.

**Comment by mworrell** [comment]
I am wondering if we couldn't just use some random bytes from crypto for the unique message id.

**Comment by technion** [comment]
I'm unfamiliar with the randomness requirements of a message id - given the existing code used now() I'd assumed "unique" was suitable.

Certainly happy to rework this if it's not the case. But I'm interested in what's going on with the tests.

**Comment by seriyps** [comment]
I think much better replacement will be smth like

```
lists:flatten([io_lib:format("~2.16.0b", [X]) || <<X>> <= crypto:rand_bytes(16)])
```

**Comment by seriyps** [comment]
Also, as general suggestions:

In Erlang it's not a good idea to give generic names to modules (like your 'compat' module), since modules nimespace is flat and clashes are possible with other applications. So, you usualy want to prefix your module like `smtp_compat`.

Also, for feature-checking possible better solution will be `erlang:is_builtin(erlang, unique_integer, 0)` instead of `try-catch`. But I'm not sure which one is really better.

**Comment by technion** [comment]
>Also, for feature-checking possible better solution will be  

Of course I don't mind what direction is taken, but I pulled my strategy from the official compatibility library:
http://www.erlang.org/doc/apps/erts/time_compat.erl

And yes, I agree it should have a better name. I'd rather not make commits around that until I hear about a strategy likely to end up merged.

**Comment by mworrell** [comment]
See also #113

**Comment by seriyps** [comment]
Might be closed? Was fixed by https://github.com/Vagabond/gen_smtp/pull/155

**Comment by mworrell** [comment]
Yes, let's close it.
